version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: main
  labels:
  - dependencies
  ignore:
  - dependency-name: cssnano
    versions:
    - 5.0.2
  - dependency-name: webpack
    versions:
    - 4.46.0
    - 5.31.2
    - 5.34.0
    - 5.35.0
    - 5.36.1
  - dependency-name: "@types/react"
    versions:
    - 17.0.4
  - dependency-name: postcss
    versions:
    - 8.2.13
  - dependency-name: "@types/jest"
    versions:
    - 26.0.23
  - dependency-name: eslint
    versions:
    - 7.25.0
  - dependency-name: ts-loader
    versions:
    - 9.0.0
  - dependency-name: sass
    versions:
    - 1.32.8
  - dependency-name: "@babel/core"
    versions:
    - 7.13.15
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 2.34.0
    - 4.21.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
    - 4.2.4
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 2.34.0
    - 4.19.0
  - dependency-name: lerna
    versions:
    - 3.22.1
    - 4.0.0
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: webpack-dev-server
    versions:
    - 3.11.2
  - dependency-name: websocket-extensions
    versions:
    - 0.1.4
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: source-map-loader
    versions:
    - 1.1.3
  - dependency-name: style-loader
    versions:
    - 2.0.0
  - dependency-name: eslint-config-prettier
    versions:
    - 6.15.0
  - dependency-name: cross-env
    versions:
    - 7.0.3
